
version: '2'
services:
  lede-build:
    build:
      context: .
    image: lede-builder
    container_name: lede-builder
    environment:
      DEBIAN_FRONTEND: noninteractive
      CONFIG_FILE: /lede/config/N1.config
      REPO_URL: https://github.com/coolsnowwolf/lede.git
      REPO_BRANCH: master
    volumes:
      - ~/Downloads/openwrt-firmware:/lede/firmware
