version: '2'
services:
  openwrt-build:
    build:
      context: .
    container_name: openwrt-builder
    environment:
      DEBIAN_FRONTEND: noninteractive
      TARGET: ax3600
      REPO_URL: https://github.com/rmandrad/openwrt.git
      REPO_BRANCH: qualcommax-nss-6.1
    volumes:
      #- ~/openwrtHome/openwrt-firmware:/openwrt/firmware
      - ./openwrtHome/firmware:/openwrt/firmware
      #- ./openwrtHome/src:/openwrt/src


