
version: '2'
services:
  openwrt-build:
    build:
      context: .
    image: openwrt-builder
    container_name: openwrt-builder
    environment:
      DEBIAN_FRONTEND: noninteractive
      CONFIG_FILE: /openwrt/config/N1.config
      REPO_URL: https://github.com/coolsnowwolf/lede.git
      REPO_BRANCH: master
    volumes:
      - ~/Downloads/openwrt-firmware:/openwrt/firmware
