
name: Build firmware

on:
  push:
    tags:
      - v*
      - master-*

env:
  REPO_URL: https://github.com/coolsnowwolf/lede.git
  REPO_BRANCH: master

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    name: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target: [N1]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Prepare
        run: |
          echo "CONFIG_FILE=$GITHUB_WORKSPACE/config/${{ matrix.target }}.config" >> $GITHUB_ENV
          echo "FIRMWARE_DIR=/openwrt/firmware" >> $GITHUB_ENV
          echo "FIRMWARE_TAG=${{ matrix.target }}_${GITHUB_REF##*/}_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          if [[ $GITHUB_REF =~ ^refs\/tags/v[0-9]+(\.[0-9]+){1,2} ]]; then
            echo "IS_VERSION_TAG=1" >> $GITHUB_ENV
          fi

      - name: Compile
        id: compile
        run: |
          sh scripts/build.sh
          find src/bin/targets/**/packages | xargs rm -rf
          find src/bin/targets -name "*sysupgrade*bin*" | xargs -i mv -f {} $FIRMWARE_DIR
          find src/bin/targets -name "*combined*img*" | xargs -i mv -f {} $FIRMWARE_DIR
          echo "::set-output name=status::success"

      - name: Upload artifact
        uses: actions/upload-artifact@main
        if: steps.compile.outputs.status == 'success'
        with:
          name: Openwrt_${FIRMWARE_TAG}
          path: ${{ env.FIRMWARE_DIR }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          draft: true
          files: |
            ${{ env.FIRMWARE_DIR }}/*.bin
            ${{ env.FIRMWARE_DIR }}/*.img
            ${{ env.FIRMWARE_DIR }}/*.gz
            ${{ env.FIRMWARE_DIR }}/*.zip

      - name: Upload firmware to OSS
        uses: tvrcgo/upload-to-oss@v0.1.1
        if: env.IS_VERSION_TAG == 1
        with:
          key-id: ${{ secrets.OSS_KEY_ID }}
          key-secret: ${{ secrets.OSS_KEY_SECRET }}
          region: oss-cn-shenzhen
          bucket: tvrcgo
          asset-path: ${{ env.FIRMWARE_DIR }}
          target-path: /openwrt-firmware/${FIRMWARE_TAG}
