
name: build N1

on:
  pull_request:
    branches:
      - master
  push:
    tags:
      - v*
      - master-*
    paths:
      - config/N1.config

env:
  REPO_URL: https://github.com/coolsnowwolf/lede.git
  REPO_BRANCH: master
  DEVICE_NAME: N1
  CONFIG_FILE: $GITHUB_WORKSPACE/config/N1.config

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Compile
        id: compile
        run: |
          sh scripts/build.sh
          cd src/bin/targets/*/*/
          rm -rf packages
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          echo "::set-output name=status::success"

      - name: Upload artifact
        uses: actions/upload-artifact@main
        if: steps.compile.outputs.status == 'success'
        with:
          name: Openwrt_firmware_${{ env.DEVICE_NAME }}_${{ env.BUILD_TIME }}
          path: ${{ env.FIRMWARE }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          draft: true
          files: |
            ${{ env.FIRMWARE }}/*.img
            ${{ env.FIRMWARE }}/*.gz

      - name: Upload firmware to OSS
        uses: tvrcgo/upload-to-oss@v0.1.1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          key-id: ${{ secrets.OSS_KEY_ID }}
          key-secret: ${{ secrets.OSS_KEY_SECRET }}
          region: oss-cn-shenzhen
          bucket: tvrcgo
          asset-path: ${{ env.FIRMWARE }}
          target-path: /openwrt-firmware/${{ env.DEVICE_NAME }}-${{ env.BUILD_TIME }}
