
name: build N1

on:
  pull_request:
    branches:
      - master
  push:
    tags:
      - v*
    paths:
      - config/N1.config

env:
  REPO_URL: https://github.com/coolsnowwolf/lede.git
  REPO_BRANCH: master
  DEVICE_NAME: N1
  CONFIG_FILE: config/N1.config

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Compile
        id: compile
        run: |
          sh ./entrypoint.sh
          cd bin/targets/*/*
          rm -rf packages
          echo "::set-env name=FIRMWARE::$PWD"
          echo "::set-env name=BUILD_TIME::$(date +"%Y%m%d%H%M")"
          echo "::set-output name=status::success"

      - name: Upload firmware
        uses: actions/upload-artifact@main
        if: steps.compile.outputs.status == 'success'
        with:
          name: Openwrt_firmware_${DEVICE_NAME}_${{ env.BUILD_TIME }}
          path: ${{ env.FIRMWARE }}
